# action.yml
name: "conventionalcommits-checker"
author: BLumia
branding:
  icon: "check"
  color: "black"
description: "check commits inside a Pull Request and see if it matches Conventional Commits guideline"
inputs:
  github_token:
    description: "action github token"
    required: false

runs:
  using: "composite"
  steps:
    - name: debug checks
      shell: bash
      run: |
        echo "Debug: Checking PR"
        echo "Event name: ${{ github.event_name }}"
        echo "Action: ${{ github.action }}"
        echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
        echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
        echo "PR Body: ${{ github.event.pull_request.body }}"