name: Test Conventional Commits

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run action
        run: |
          echo "Running action.yml"
          ls -la action.yml
          cat action.yml